### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by KevinOl** [datatrans/payment-button#13] opened 2020-07-23 09:32 UTC
Hi,

if I cancel the apple pay process the first time and click on the apple pay button again, I am getting the following error in console,

`InvalidStateError: The object is in an invalid state.` from payment-button-1.0.0.js

Idea?

Thanks

**Comment by pstadler** [comment] 2020-07-24 08:01
Hey Kevin

Thanks for the report. We were unable to reproduce this. What we tried:
- canceling & starting payment multiple times (iOS, MacOS)
- toggling the component and starting & canceling payments

This all worked for us with Safari 13.1.2.

**Comment by KevinOl** [comment] 2020-07-24 12:53
mhhhh still happening for me.

**Comment by pstadler** [comment] 2020-07-24 13:01
Alright, need to test this on mobile

**Comment by KevinOl** [comment] 2020-08-01 11:37
Any news?

**Comment by pstadler** [comment] 2020-08-01 12:11
Going to tackle this next week.

**Comment by pstadler** [comment] 2020-08-03 07:01
After trying this on an iPhone XS with iOS 13.5.1, I'm still unable to reproduce this. Both examples in the master branch (React / non-React) are working well for me and don't throw such errors. I'm closing this now for good.

P.S. If the problem persists, please send an example project containing code and exact steps to reproduce the problem to support@datatrans.ch

**Closed by pstadler** 2020-08-03 07:01 UTC
